# Generated by Django 3.1.2 on 2020-10-24 10:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoIterator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_names', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_content', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2020, 10, 24, 10, 58, 46, 495586, tzinfo=utc))),
                ('due_time', models.DateTimeField(default=datetime.datetime(2020, 10, 24, 10, 58, 46, 495586, tzinfo=utc))),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Done')])),
                ('list_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HauntedCheese.todoiterator')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
