# Generated by Django 3.1.2 on 2020-10-24 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HauntedCheese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='list_iterator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HauntedCheese.todoiterator'),
        ),
        migrations.AddField(
            model_name='todoiterator',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='list_title',
            field=models.CharField(max_length=255),
        ),
    ]
