# Generated by Django 3.1.2 on 2020-10-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HauntedCheese', '0002_auto_20201024_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='list_content',
            new_name='list_description',
        ),
    ]
